"""
Django settings for GOSPORT_RESERVAS project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-#-^f@sf7j=+%*hs)a3ywnbm-tst@$e5k&8i3t^p!ny^!%%h=j6'

DEBUG = True

ALLOWED_HOSTS = ['*']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # apps del proyecto
    'login_register',
    'reservas',
    'usuarios',
    'productos',
    'reportes',
    'canchas',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'GOSPORT_RESERVAS.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ✔ carpeta global templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'GOSPORT_RESERVAS.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


LANGUAGE_CODE = 'es-co'  # 🔥 mejor para tu proyecto

TIME_ZONE = 'America/Bogota'

USE_I18N = True
USE_TZ = True


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',  # ✔ forma moderna
]


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# 🔥 CONFIGURACIÓN DE LOGIN (CORREGIDA)
LOGIN_URL = '/auth/login/'              # a dónde manda si no está logueado
LOGIN_REDIRECT_URL = '/reservas/'      # después de iniciar sesión
LOGOUT_REDIRECT_URL = '/auth/login/'   # después de cerrar sesión


# 🔥 FIX PARA NGROK
CSRF_TRUSTED_ORIGINS = [
    "https://modulator-slit-frolic.ngrok-free.dev",
    "https://*.ngrok-free.app",
    "https://*.ngrok-free.dev",
]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'