# Generated by Django 6.0.3 on 2026-04-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_email_usuario_password_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario')], max_length=20),
        ),
    ]
