# Generated by Django 6.0.4 on 2026-04-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
