# Generated by Django 6.0.3 on 2026-04-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
