# Generated by Django 4.2.30 on 2026-06-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
