# Generated by Django 4.2.30 on 2026-07-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_cancha_latitud_cancha_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
