# Generated by Django 6.0.4 on 2026-04-11 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_cancha_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancha_nombre', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=30)),
                ('horario', models.CharField(max_length=30)),
                ('personas', models.IntegerField(default=1)),
                ('horas', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('imagen', models.CharField(blank=True, max_length=200)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cancha',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
